### ISSUE TITLE
_POST is null

### ISSUE THREAD

**Issue by martincumt** [dedemao/alipay#1]
notify_url 和支付宝设置的回调地址是不是一个？我这notify_url 回调方法里面 $_POST 为空怎么回事

**Comment by dedemao** [comment]
notify_url是你支付时，向支付宝接口传递的其中一个参数，不一定是支付宝设置的

**Comment by LeoRoll** [comment]
异步回调，同样的问题，支付成功后，拿到支付宝的返回信息，openssl_verify 验签失败，$result 为空
