### ISSUE TITLE
authorize.php文件中参数更新

### ISSUE THREAD

**Issue by Monkeyratio** [dedemao/alipay#4]
网页授权获取用户信息中scope的值为auth_user,已经替代之前的auth_userinfo。
alipay.user.info.share已经替代了alipay.user.userinfo.share
$userinfo得到的用户信息参数['alipay_user_info_share_response']已经替代了['alipay_user_userinfo_share_response']

**Comment by ruffiant** [comment]
没更新,好像不好用

**Comment by dedemao** [comment]
参数不更改也可以使用
